title: "Shreyansh's ML/DL Blog"
description: "Paper reviews, explanations, and experiments in ML/DL"
baseurl: "" # leave empty unless hosted at a subpath
url: "https://your-username.github.io" # change to your actual GitHub Pages URL
theme: null # critical: disables Jekyll theme gem lookup
markdown: kramdown
permalink: pretty
timezone: Asia/Kolkata
future: true



# Optional:
paginate: 5
paginate_path: "/page:num"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections (optional)
collections:
  posts:
    output: true
