title: "Shreyansh's ML/DL Blog"
description: "Paper reviews, explanations, and experiments in ML/DL - focusing on computer vision, facial recognition, and GPU-accelerated computing"
url: "https://shrrynsh.github.io"
baseurl: "/site.github.io"
theme: null
markdown: kramdown
permalink: pretty
timezone: Asia/Kolkata
future: true

# Author information
author:
  name: "Shreyansh"
  bio: "ML/DL researcher working with facial recognition models, GPU computing, and computer vision datasets"
  location: "India"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/shrrynsh"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/yourusername"

# Site settings
lang: en-US
locale: en-US
repository: "shrrynsh/site.github.io"

# Build settings
highlighter: rouge
incremental: false
safe: true

# Pagination
paginate: 5
paginate_path: "/page:num"

# SEO and social
twitter:
  username: yourusername
social:
  name: Shreyansh
  links:
    - "https://github.com/shrrynsh"
    - "https://twitter.com/yourusername"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Shreyansh"
      show_date: true
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CHANGELOG.md

# Include files
include:
  - _pages

# Research focus areas for metadata
research_areas:
  - "Computer Vision"
  - "Facial Recognition"
  - "GPU Computing"
  - "Deep Learning"
  - "Image Processing"
  - "Machine Learning"
