title: "Shreyansh's ML/DL Blog"
description: "Paper reviews, explanations, and experiments in ML/DL"
url: "https://shrrynsh.github.io"
baseurl: "/site.github.io"
theme: null # critical: disables Jekyll theme gem lookup
markdown: kramdown
permalink: pretty
timezone: Asia/Kolkata
future: true



# Optional:
paginate: 5
paginate_path: "/page:num"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections (optional)
collections:
  posts:
    output: true
